---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: registry
spec:
  encryptedData:
    users: AgAA9PZGQoy64yo0jhdC5HlRcz6OIBQEpcLtH9KYo/k6zy8+0bXNw3Rv3j97+DH5EM8mSfPJa7W0ltQ84D/5u/6yoVLjLPoiQmsgGQwXUFD1ms2KIDdBF5FPVPGMdTsu7ap4MRcp56nSWAFm80NefGbTLpCCdSD7vn9/QvI1g+UdmFOsU5R6gNdSLCeVGjP93ynC/XzgE7B8bBuaNd/3hAYMh3UFmnuMlrf7Jcv7U4JXoYvA2Bu94UIQMaAwjjK1vI/Wo/fkZu75EpM7g7fzSYXVZZettqVzW8nOr7iQJwq6WjCvFi78YE9u1GfGSC8vBIicc5Nk9qcfW84krbyBzOvp3HJ8QOUlIzT9nTsJiV/Bv5uOVyqzhQbhYBOwuddzQpA0kvJGMHU7fasopiOmS0OU9IoQcaGj8N0gjKd+QDk1qvYSUfp0HYaaGQHiYN6Hd7Py8kUQhIuTspFxo9h2/YlYi6hsMe4DXAUkNo8tbSif4x6N1AW2SB90hPsJPU2l7aBnUnf5VOcn3dyixFMOFmpyAq8Ti9yu7zgLlNV5EDbknl7zk0QtmHhBL6jiK7f+XSHSFGlVRpOdWHLj1VRIZLR1pVFCU2gE2fYWWrZotiS7CHiP4RNTHTELJ8o5bJM3OsHmfNfboCrv7CJvlS0kkgvMFBsvIc5jURbIyR/O03TSaSnTjxNyHqBJtBCdPksvqJnBH/yblXO35t2pQjIceINt0oT5YctCzLUg/bYQF45XQ9TlamO2MQkTd6PPtWKbxrlRUMdlIkxQJnD2EIeEa9Mht2mdj/3U1M0k
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: registry
