apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- credentials.yaml
- manifests.yaml

# # Create a Sealed Secret
# k create secret generic credentials --namespace=registry \
# --from-literal="username=<username>" \
# --from-literal="password=<password>" \
# --dry-run=client --output yaml | kubeseal > credentials.yaml --format yaml

namespace: registry
