# ./scripts/env-to-file.sh --file=general-config.yaml | k apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: general-config
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
data:
  APP_DOMAIN: "$APP_DOMAIN"
  APP_CONTAINER_REPO: "$APP_CONTAINER_REPO"
