apiVersion: kustomize.config.k8s.io/v1beta1

# kubectl apply -k .
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: scheduler
    env: production
    version: v1

# Without it, Kustomize will not know what to do with the rollout resource (kind=rollout).
configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform-kustomize-v5.yaml

generatorOptions:
  disableNameSuffixHash: true

namespace: default

resources:
- rollout.yaml

# kustomize edit set image scheduler-image=newName:newTag
images:
- name: scheduler-image
  newName: ewr.vultrcr.com/blog/app
  newTag: 233d13b
