# ./scripts/env-to-file.sh --file=argo/rollouts/application-helm.yaml | k apply -f -
# k describe application.argoproj.io --namespace argocd argo-rollouts-helm
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts-helm
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
  source:
    chart: argo-rollouts
    repoURL: https://argoproj.github.io/argo-helm
    # https://github.com/argoproj/argo-helm/blob/argo-rollouts-2.39.5/charts/argo-rollouts/Chart.yaml#L2C1-L2C19
    targetRevision: 2.39.5
    helm:
      valuesObject:
        controller:
          replicas: 2
        dashboard:
          enabled: true
          replicas: 1
          ingress:
            enabled: false
