apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-blog-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
