apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    env: production
    version: v1

# Without it, Kustomize will not know what to do with the rollout resource (kind=rollout).
configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform-kustomize-v5.yaml

# ./scripts/env-to-file.sh --env=app/argocd/base/.env --file=app/argocd/base/config.example.yaml | kubeseal > app/argocd/base/credentials.yaml --format yaml
resources:
- credentials.yaml
- public-pvc.yaml

generatorOptions:
  disableNameSuffixHash: true

namespace: default

components:
- ../components/blog-image
- ../components/blog-pre-sync-image
