apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

# ./scripts/env-to-file.sh --env=app/argocd/base/.env --file=app/argocd/base/config.example.yaml | kubeseal > app/argocd/base/credentials.yaml --format yaml
resources:
- credentials.yaml
- app-blog-pvc.yaml
