# ./scripts/env-to-file.sh --file=argo/cd/application.yaml | k apply -f -
# k describe application.argoproj.io --namespace gitops argo-cd
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: gitops
  # # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: gitops
    server: https://kubernetes.default.svc
  source:
    path: argo/cd
    repoURL: https://github.com/allysonsilva/blog-k3s
    targetRevision: HEAD
    plugin:
      name: envsubst
      env:
        - name: DOMAIN
          value: ${APP_DOMAIN}
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
