---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: no-verify-tls
  namespace: argocd
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.$APP_DOMAIN`)
      priority: 30
      services:
        - name: argocd-server
          port: 80
          serversTransport: no-verify-tls
    - kind: Rule
      match: Host(`argocd.$APP_DOMAIN`) && Headers(`Content-Type`, `application/grpc`)
      priority: 31
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
          serversTransport: no-verify-tls
