# kustomize build --enable-helm argo/cd | k apply -f - --dry-run=client
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: gitops

# argocd admin initial-password -n gitops
# kubectl -n gitops get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  releaseName: argo-cd
  namespace: gitops
  version: 7.5.2
  # valuesInline:
  #   global:
  #     ## Used for ingresses, certificates, SSO, notifications, etc.
  #     domain: argocd.${APP_DOMAIN}
  valuesFile: values.yaml
