apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- manifests.yaml

namespace: uptime-kuma

# replacements:
#   - source:
#       name: general-config
#       kind: ConfigMap
#       version: v1
#       namespace: uptime-kuma
#       fieldPath: data.APP_DOMAIN
#     targets:
#     - select:
#         kind: IngressRoute
#         name: uptime-kuma
#         namespace: uptime-kuma
#       fieldPaths:
#         - spec.routes.0.match
#       options:
#         delimiter: "."
#         index: 1
#         create: true
