apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors-assets
  namespace: default
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList:
      - "*"
