apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hsts-headers
  namespace: default
spec:
  headers:
      stsPreload: true
      forceSTSHeader: true
      stsSeconds: 31536000
      stsIncludeSubdomains: true
