apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: noindex-page-headers
  namespace: default
spec:
  headers:
    customResponseHeaders:
      X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
