apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: secure-headers
  namespace: default
spec:
  headers:
    sslProxyHeaders:
      X-Forwarded-Proto: https
    hostsProxyHeaders:
      - X-Forwarded-Host
    browserXssFilter: true
    contentTypeNosniff: true
    # referrerPolicy: same-origin
    # customFrameOptionsValue: SAMEORIGIN
    # ContentSecurityPolicy: "default-src * 'self' https: data: blob: 'unsafe-inline' 'unsafe-hashes' 'unsafe-eval'; upgrade-insecure-requests;"
    # PermissionsPolicy: >-
    #   camera 'none'; geolocation 'none'; microphone 'none'; payment 'none';
    #   usb 'none'; midi 'none'; interest-cohort 'none'; fullscreen 'self';
    customResponseHeaders:
      # X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
      server: ""
