# 1 - ./scripts/env-to-file.sh --file=app/certificate/secret.yaml | k apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
data:
  # base64 encoded $CF_DNS_API_TOKEN
  # be sure you are generating an API token and not a global API key https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens
  api-token: $CF_DNS_API_TOKEN
