# ./scripts/env-to-file.sh --file=soketi/application.yaml | k apply -f -
# k describe application.argoproj.io --namespace argocd soketi
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soketi
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: soketi
    server: https://kubernetes.default.svc
  source:
    path: soketi
    repoURL: https://github.com/allysonsilva/blog-k3s
    targetRevision: HEAD
    plugin:
      name: envsubst
      env:
        - name: DOMAIN
          value: ${APP_DOMAIN}
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - CreateNamespace=true
