apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yaml
- credentials.yaml
- service.yaml
- ingress.yaml
- monitor.yaml

# # Create a Sealed Secret
# k create secret generic credentials --namespace soketi --from-env-file=.env --dry-run=client --output yaml | kubeseal > credentials.yaml --format yaml

namespace: soketi

transformers:
- |-
  apiVersion: builtin
  kind: PatchTransformer
  metadata:
    name: notImportantHere
  patch: '[{"op": "replace", "path": "/metadata/namespace", "value": "monitoring"}]'
  target:
    group: monitoring.coreos.com
    kind: ServiceMonitor
    name: soketi-blog

# kustomize build --enable-helm . | kubectl apply -f -
helmCharts:
- name: soketi
  # @see https://github.com/soketi/charts/tree/soketi-2.0.0/charts/soketi
  repo: https://helm.soketi.app
  releaseName: soketi
  namespace: soketi
  version: 2.0.0
  valuesInline:
    nameOverride: "blog"
    app:
      extraEnv:
        - name: SOKETI_DEFAULT_APP_ID
          valueFrom:
            secretKeyRef:
              name: credentials
              key: SOKETI_DEFAULT_APP_ID

        - name: SOKETI_DEFAULT_APP_KEY
          valueFrom:
            secretKeyRef:
              name: credentials
              key: SOKETI_DEFAULT_APP_KEY

        - name: SOKETI_DEFAULT_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: credentials
              key: SOKETI_DEFAULT_APP_SECRET

        - name: SOKETI_DEFAULT_APP_MAX_CONNS
          valueFrom:
            secretKeyRef:
              name: credentials
              key: SOKETI_DEFAULT_APP_MAX_CONNS

        - name: SOKETI_METRICS_ENABLED
          value: 'true'
        - name: SOKETI_METRICS_SERVER_PORT
          value: "9601"
        - name: SOKETI_METRICS_DRIVER
          value: "prometheus"
    serviceMonitor:
      enabled: false
  # valuesFile: values.yaml
