# ./scripts/env-to-file.sh --file=mysql/application.yaml | k apply -f -
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
spec:
  project: default
  destination:
    namespace: database
    server: https://kubernetes.default.svc
  source:
    path: mysql
    repoURL: https://github.com/allysonsilva/blog-k3s
    targetRevision: HEAD
    # kustomize:
    #   commonAnnotationsEnvsubst: true
    #   commonAnnotations:
    #     app-source: ${ARGOCD_APP_NAME}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
