# ./scripts/env-to-file.sh --file=app/argocd/shared/application.yaml | k apply -f -
# k describe application.argoproj.io --namespace argocd app-shared
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-shared
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: app/argocd/shared
    repoURL: https://github.com/allysonsilva/blog-k3s
    targetRevision: HEAD
    plugin:
      name: envsubst
      env:
        - name: DOMAIN
          value: ${APP_DOMAIN}
  # Disable autosync in application spec:
  syncPolicy: {}
