---
# argocd account generate-token --account management --grpc-web
# k create secret generic argocd-api-token --namespace default --from-env-file=.env.argocd --dry-run=client --output yaml | kubeseal > argocd-api-token.yaml --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-api-token
  namespace: default
spec:
  encryptedData:
    ARGOCD_TOKEN: AgB6/czj+SME6IdUriaGvT2FaeRte7Xlp3jYzvpi3ZW46lVxDjoiJU/zyh9mBcE1mZ0niu6oKeRKK+dGEnawL8R+psJEhidfgcuFxn5JVw7rxTtB/1l94TegPg2//6VSBw+QAUfQ0iF9cUFVmBMTYHWgFRPUvCWpB4rKvHznJkwJIZSKLYK5SIUlx4MwrVxq6LbRvKDPkE5yzHRp39ACBkCFTBBunevK6+EF54930rCfrMFfeuz270G+1lEBhi9sftbiuiW1NZ1Jno4QGqL8xIAOk1OffxTiCUveXAlOdQiIhxBkxL41T8NyQinfgoPryb5fvALoVydWLSDJ39lb3gEz6841teXKw0ZCy+sKC/8KQC6Rkm4qfx5v34lnjNsnHWxmo905RBbNpx1j9JFCvUcQJ9VLS4OlUOXY1eSR98jgc1TwMFDtotN4EHsutwg9pNbUdbRGl6n7XtBN5R83ZXP5xWPZP/oEiRZmGwG1mWy13RapSAd7t9ZGndecH9RP0S+T6uf2D7e4TYuwZu1wtKEuqlHAXacbra/EUxq0yclXBiIeEIzjg42BPkD5e7zOfh7IlTT+D4Tnyf9MkES8ZNjGDt8hQa5fioi+opYX2aDnJ1+E30EaFB8UlOgt/Un/IYXUCYBGsQkXG/c3tFqG+yMXG4kr1+ff6s3rstUXnjjc9SvPfPGmsLXdH2w7RpPRAfdqDArJ2nAHvX9YXHOaaMvl4uDlQOvN08lqFmmtTZqFlmJHngbeL9D37iGMtSFVX0PfbCtqqtPB89TOyeA5A7I7PJ1Xq5DRP1gl7f+81DrvPFp3OJGRE6pu+Pt/73TYIZmUe2LqEJkr66UyeZUHEEjL7bB/1ST9o97/bP7ygV1q5Z04gQdlNnS4M/hnU48Kzs2HWBZuHH4OWjBglh7V1R91oZU53ha4NGpc2MXUztpKwDXQmhwKMP8+eXnog1Y2S/HjS0WGdDWcUUNyZuemgyKnl17ucXTUiEpDE4zexgh2KAcuv0Gas2x81AWDncdvIOkeojk=
  template:
    metadata:
      creationTimestamp: null
      name: argocd-api-token
      namespace: default
