---
# argocd account generate-token --account admin --grpc-web
# k create secret generic argocd-api-token --namespace default --from-env-file=.env.argocd --dry-run=client --output yaml | kubeseal > argocd-api-token.yaml --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-api-token
  namespace: default
spec:
  encryptedData:
    ARGOCD_TOKEN: AgB1AN4SUKiSl33vVePY84WXNo0brlDY7UTRy+C+JouZNZxg+5b5JC8CTbt9IWnV93h4KwhpyGcS2hNV6KjcZpudjPAtUc9xJUBo7qrVTL+L22UF3yIoLkFbfH8ptF9B6jF8y1KiB5ztCyxMQZJhQ2gdFKiegxJaieqwK9KEZ7Y9Y6vKll4swWnWGp8XRZFUHcyuWoLi2EL6fJd0trEZ+sfVgNr/JWk1ONzYcuBnPCSdJ7GADfwnNyOBCgFvNnrBEhtWfEZqYtUVQQNFj2G9SHMyuZscGBqt8KpN/cqgxMk3fsGSgMrXFeSUwvtyT7lP5WchQFrn+HHVTYPu0o+KjYuQJb+Zn7h9gFRVv/jQYo9Idv3ahXPBt9lHDT89+CVvpWWLw6fnxdNuMfNL3p+jbAUKJNeDCK916LhgwtkSMuBBH0A+xhOIx9SZyUh7J9i+foX+jcmeXZVubBrZrv65k6Iqi3gUvG1diisdtGjJtTmuaxhKrA8SIYBLshxH9RTsvS4a81UGh1Mb84nvessgSRB5dsVnWsHi2osw60aiwgXTQtqKMoFIAXsZMrYH2Pq9CEuAQEnqdrSe47KiSusgiXGeFL9IhwevA1/Z+B3ctu2t/qp1ae90SqkRwFIvezbOrSiONh1CbTLgOxrW1ZvJDLh8fqthqnH0goIWir8RqSOAdjD/GGgD6VnEID55L6I+8bhTlqkbK7bEmRZnG4zNsp/c8GilcekHaVugd7WvzfeXv5JyfGBjMNDHpdWnZvksgk0zXcAwhJMVZyDNz8H7EIveWCh/V+PUdGUon4M9s2FJUQgspwLVfFvmJoJnegtRplWMq9BCL/zdiz80ckz8i8raOq8/hi97yPUqwVa+Nw7P1+hqtOUOWLNYxyEvouVZCq1/MKaPBMdwvz9gaa+iCX99hBNJyumHmvKsIWtfuYTR32QPOcs0EiauLQwMuYa/eXt9e/p/ofq2hFYANF7AWaNe4zT2EkTmen9xxN+u+WMtk6o7mB2ob5y9fQHr4Q==
  template:
    metadata:
      creationTimestamp: null
      name: argocd-api-token
      namespace: default
