apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: blog
    env: production
    version: v1

generatorOptions:
  disableNameSuffixHash: true

namespace: default

# ./scripts/env-to-file.sh --env=app/argocd/shared/.env --file=app/argocd/shared/config.example.yaml | kubeseal > app/argocd/shared/credentials.yaml --format yaml
resources:
- credentials.yaml
- argocd-api-token.yaml
- app-blog-pvc.yaml
