apiVersion: kustomize.config.k8s.io/v1beta1

# kubectl apply -k .
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: blog

resources:
- ../base
- pre-sync.yaml
- preview-health-check.yaml
- rollout.yaml
- service-active.yaml
- service-preview.yaml
- ingress.yaml

# kustomize edit set image blog-image=newName:newTag
images:
- name: blog-image
  newName: ewr.vultrcr.com/blog/app
  newTag: 217c6f8e096b995bf6c18dbe1e28babbd9223864
- name: blog-image-pre-sync
  newName: ewr.vultrcr.com/blog/app
  newTag: init-217c6f8e096b995bf6c18dbe1e28babbd9223864
