apiVersion: kustomize.config.k8s.io/v1beta1

# kubectl apply -k .
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: blog
    env: production
    version: v1

# Without it, Kustomize will not know what to do with the rollout resource (kind=rollout).
configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform-kustomize-v5.yaml

generatorOptions:
  disableNameSuffixHash: true

namespace: default

resources:
- ../base
- pre-sync.yaml
- preview-health-check.yaml
- rollout.yaml
- service-active.yaml
- service-preview.yaml
- ingress.yaml

# kustomize edit set image blog-image=newName:newTag
images:
- name: blog-image
  newName: ewr.vultrcr.com/blog/app
  newTag: b788aee
