apiVersion: kustomize.config.k8s.io/v1beta1

# kubectl apply -k .
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: blog

resources:
- ../base
- pre-sync.yaml
- preview-health-check.yaml
- rollout.yaml
- service-active.yaml
- service-preview.yaml
- ingress.yaml
