# @see https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/
apiVersion: v1
kind: Pod
metadata:
  name: blog-pre-sync
  # namespace: default
  labels:
    app: blog-pre-sync
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    # argocd.argoproj.io/sync-wave: "1"
spec:
  restartPolicy: OnFailure
  maxRetries: 3
  imagePullSecrets:
    - name: vultr-cr-credentials
  volumes:
    - name: app-blog-shared
      persistentVolumeClaim:
        claimName: app-blog-pvc
  containers:
    - name: app-blog-pre-sync
      image: blog-image
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1"
          memory: "512Mi"
      args:
        - /bin/sh
        - -c
        - |
          # if [ -f /app-data/.copied ]; then
          #   echo "Arquivos já foram copiados anteriormente. Pulando..."
          #   exit 0
          # fi

          if [ -d "$REMOTE_SRC" ]; then
            echo "Copiando arquivos de $REMOTE_SRC para /app-data..."
            mkdir -p /app-data
            sudo rsync -a --chown=${USER_NAME}:${USER_NAME} "$REMOTE_SRC"/ /app-data/
            echo "Cópia concluída!"
            # Cria o marcador
            # touch /app-data/.copied
            exit 0
          else
            echo "Diretório $REMOTE_SRC não encontrado!"
            exit 1
          fi

          # HASH_FILE="/app-data/.app_hash"
          # CURRENT_HASH=$(find "$REMOTE_SRC" -type f -exec sha256sum {} + | sort | sha256sum | awk '{print $1}')

          # if [ -f "$HASH_FILE" ]; then
          #   PREVIOUS_HASH=$(cat "$HASH_FILE")
          #   if [ "$CURRENT_HASH" = "$PREVIOUS_HASH" ]; then
          #     echo "Nenhuma alteração detectada no conteúdo de $REMOTE_SRC. Pulando cópia."
          #     exit 0
          #   fi
          # fi

          # echo "Alterações detectadas. Copiando arquivos para /app-data..."
          # mkdir -p /app-data
          # cp -r "$REMOTE_SRC"/* /app-data

          # echo "$CURRENT_HASH" > "$HASH_FILE"
          # echo "Cópia concluída e hash atualizado."
      # Note:
      # The command field corresponds to ENTRYPOINT,
      # and the args field corresponds to CMD in some container runtimes.
      # command:
      #   - php
      # args:
      #   - artisan
      #   - migrate:status
      env:
        - name: FORCE_MIGRATE
          value: "true"
        - name: IS_PRE_SYNC
          value: "true"
      envFrom:
        - secretRef:
            name: app-environment-configs
      volumeMounts:
        - name: app-blog-shared
          mountPath: /app-data
