apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: preview-health-check
spec:
  args:
    - name: preview-url
  metrics:
    # Promoção só ocorre após 3 respostas bem-sucedidas.
    # Se 3 erros ocorrerem antes disso, rollback automático.
    - name: health-check
      interval: 5s
      count: 12
      successCondition: result == 200
      # Especifica que são necessários 3 sucessos consecutivos para que a análise seja considerada bem-sucedida e a promoção ocorra.
      consecutiveSuccessLimit: 3
      # Se você omitir o failureCondition, o Argo não vai saber o que conta como erro, e o failureLimit não terá efeito → o rollout pode nunca falhar, mesmo com respostas ruins.
      failureCondition: result != 200
      # Se tiver 3 falhas (em qualquer ordem), falha a análise, não é promovido!
      failureLimit: 3
      provider:
        web:
          url: "{{args.preview-url}}"
          timeoutSeconds: 5
          jsonPath: '{.statusCode}'
