apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: sync-worker-rollout
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  metrics:
    - name: sync-worker
      successCondition: result.exitCode == 0
      provider:
        job:
          spec:
            serviceAccountName: sa-queue-worker-rollout
            restartPolicy: Never
            backoffLimit: 1
            template:
              spec:
                containers:
                  - name: trigger-sync
                    image: curlimages/curl
                    command:
                      - /bin/sh
                      - -c
                      - |
                        TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
                        curl -X POST \
                          -H "Authorization: Bearer $TOKEN" \
                          -H "Content-Type: application/json" \
                          -d '{"syncPolicy": "automatic"}' \
                          http://argocd-server.argocd.svc.cluster.local/api/v1/applications/queue-worker-rollout -o /dev/null -w "%{http_code}" -s
