apiVersion: kustomize.config.k8s.io/v1beta1

# kubectl apply -k .
kind: Kustomization

commonLabels:
  env: production
  version: v1

# Without it, Kustomize will not know what to do with the rollout resource (kind=rollout).
configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform-kustomize-v5.yaml

# ./scripts/env-to-file.sh --env=app/delivery/.env --file=app/delivery/config.example.yaml | kubeseal > app/delivery/credentials.yaml --format yaml
resources:
- credentials.yaml
- public-pvc.yaml
- pre-sync.yaml
- rollout.yaml
- service-active.yaml
- service-preview.yaml
- ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

namespace: default

# kustomize edit set image blog-image=newName:newTag
images:
- name: blog-image
  newName: ewr.vultrcr.com/blog/app
  newTag: 987c530470f9cb81e55b11a5999aba07b1f20ce3
- name: blog-image-pre-sync
  newName: ewr.vultrcr.com/blog/app
  newTag: init-987c530470f9cb81e55b11a5999aba07b1f20ce3
