---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: redis
spec:
  encryptedData:
    REDIS_ADMIN_PASSWORD: AgDN7XLNS+bzm0oQSDDKfNrqvxW9vWp4vmrMeltCY18miwwuSSy3i0iauqxCmekz9MEr4/tZ9f5jTzaU+D9OyF21ufbTIPaZQBVMNiA9dzzVfnmPeAbQQNExTMnJIsxhr/6AjmJ0T+8Vmj9NrdUUCQvSQzREFTUdKXaR8l1/YO6E7CDU2gT7Qw99EUlguiPKQqfsPbrV38JE+FSYETVkoYqkLN0RjlFXvEqWNmeWKxybu8mZUY0wzeb2X/bItM/FsSrdIqdPMlXa/1y0kyQUGr7lDpbDoYO1n5RtvrN1MUWM9IRAqVjBCE9Vckzn7ocKxkg+k5A1IiAqR5MF+ZGPU6OyU5DPuNyCVTJ6QuqqYWFX8Izm170FpWYyhbnFAIiq4hQP+A0TPGXJztbMaMoe5A+DPnG1tAGwm19oTd5CEYhdP/sxUSW3l3jL1wphGPKoR4rErYdC9RS8lC8PxfHTURLR/3eSNAnxPTxYDpw3Lxsi+WaSyT+OjaVBMrZBugicSMWhxlG5GsxxZMX+jjV3USBkC8g8C6IQYVipN4kH1yzeXQbXBjmk/wBKN4ws44+DzVQ91hYU7yAYqP5bchwXuPTpmR3tpXA3rpdL3JM26FFbrDijqnWlTpQMBU1aHT7NLrXidQ800Ie2ej7kpC41A2KVLflvVCL4tMevzzC/uqfkSEHllS+8+j7Dx8n6bgkCqtb5EYmbnNgMdwlDHMY=
    REDIS_DEFAULT_PASS: AgDAJEGiFG78z2Y0Tc12Q3eQt5cGuK6yORWNZdbMt9F2pq66LtlmGrD+WW8CPFxutyEH6PYY3OakxK+ncB7WXUslbX+7LLUOQNPQfz/TLcx+PwBmJtRowzCzQQIehb0M1KstqXk0qeyEsaQj8/FOPW/wlkadFVES0Y489Qyh/OCrqj4PpzIQAaLxkcqiGWIEg+n54XjARDPge8010+dcGnzR1SLR1dfFEVR/Qom+sGdiaNBqx2LE0p6YnM90AlTq9fmFCC0vR/No3o5EAR+54UHjAPCz13YBMbe4qtGEZjA3anLBBfJRnWP051ofkJNgZmvUTEm5qNyTc+X5Xzz3CfZjypeHSXUNQQGaHxBIsHkK2zg7F4a2Idup9kY6XNFsm4j/8M7wbnt1yATS8n1VIL9zgQxyuNtAIUcxB8L4iLn+YfxN9N/frt5ILY5WJUOVTT6ZrAPUcCd3GaUYXNOREOSgxIgjwVHV3adQiQCAy3xp8f2qjxWeD2BoXlu+RZg+2B4DqrA7ZHjBjHta9mENP6WvzPpLIZP/uSybWIIUlHd8DHpxkROR/F6K5LpHCHMd3ZkHiUERoxRMQ+k7dRnEKAzOXD6DAXuQRTIFaFLfbukC0IJwtwa5T/xLvHpcUrjAvsuBL4rn7v86cL2W53apjLoFcWkShr5oMXlgOR5wLNhY9/W4bezVR1Qf31bbgi/DGbbdlVdNnsM1ctCMg7DFXZhMTjRvl40=
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: redis
