---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: redis
spec:
  encryptedData:
    REDIS_PASS: AgC2AYit9IKPA9OYuOBGuEYXBs+6A7vHICODlFDGrhXpm6lr3lR6b8f61sLQgJ5q9PaayqIrMZkV2991cylYrsBX9FLJh3B2AidWP7ZReTycCBEWPVyku6YPYYr7HlxiJWfjoqjLIN0EhgHZ31wtvbQ3RP/qYMAtzkJBtHDdCN2FDyzThWuIurHeEFqQAnFbHgdrX0pPhS7ChwOxxtHCa0yevIrz/eexyyCPc6ejI94R2ubdhFEl3DCJ8ALnaXnAt4F1BJxRC/8NtgX/J/VXJJ63MWvnUAQT4UaN8FSh3AI2tCHZgOXRtyyPJq/PwjIZ9pMegGgNsLYBypxxjVI57WbxlCw8dsc/LeTPKUnjmCTeXZ1dBKrGAXSO9yO2/HnucIYRCjt3S34ksmx3Z3cSx6e0LhlWchD9IDoA8eDwUPC01uRKT6wZj8Vlj/QwME1TDrGbPx3fyD/ocH7CZKBRQqb3Yk1eFVdi75tVxJFtm5c3qijbaJ8kAw3/dwgwSJwJQrhSW3+fHHVGwSj+hfK68IJ9KfSzpOuHMCzFhXmlMxmijx3L3b/cdllG2fzMzpUY/Q1YWlZnzATsHzeCYIqrXc8dEsVYfExWnZCKy+0bJ6QOFBnLr2g34fg0Nu7j9V3HWpil6OV3+g+vIVJ4NUAF38SNx1ANYrZiPKUA5oRiQ8b9gyQXxb6rc64WlAwGmAMJFeXBfJnZaYnxmkFSO8yl8RbrWRzJsKk=
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: redis
